export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL'

export const JOIN_CHAT = 'JOIN_CHAT'
export const LEAVE_CHAT = 'LEAVE_CHAT'
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION'
